"""Initial migration

Revision ID: 445103ccef3d
Revises: 
Create Date: 2024-11-18 21:50:32.386255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '445103ccef3d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('audio_files',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('blob_name', sa.String(), nullable=True),
    sa.Column('file_url', sa.String(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audio_files_blob_name'), 'audio_files', ['blob_name'], unique=False)
    op.create_index(op.f('ix_audio_files_id'), 'audio_files', ['id'], unique=False)
    op.create_table('transcriptions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('audio_file_id', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('is_processing', sa.Boolean(), nullable=True),
    sa.Column('is_error', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['audio_file_id'], ['audio_files.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('audio_file_id')
    )
    op.create_index(op.f('ix_transcriptions_id'), 'transcriptions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transcriptions_id'), table_name='transcriptions')
    op.drop_table('transcriptions')
    op.drop_index(op.f('ix_audio_files_id'), table_name='audio_files')
    op.drop_index(op.f('ix_audio_files_blob_name'), table_name='audio_files')
    op.drop_table('audio_files')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
